//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donations_Software.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationUserInfo
    {
        public int DUID { get; set; }
        public Nullable<int> DonationID { get; set; }
        public Nullable<int> personalInfoID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual DonationDetail DonationDetail { get; set; }
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
