//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donations_Software.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonationDetail()
        {
            this.DonationUserInfoes = new HashSet<DonationUserInfo>();
        }
    
        public int DonationID { get; set; }
        public string DonationName { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> isMonthly { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonationUserInfo> DonationUserInfoes { get; set; }
    }
}
